version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/zeni/my-node-app/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

networks:
  my-network:
